### ISSUE TITLE
Random flip and rotation when evaluate

### ISSUE THREAD

**Issue by apollo-time** [mokemokechicken/reversi-alpha-zero#16]
I see you did random flip and rotation in the Player's expand_and_evaluate function.
I think this is need when add data for training, but don't necessary when evaluate for selecting action.
How about it?

**Comment by mokemokechicken** [comment]
Hi @apollo-time

It is written in DeepMind's [paper](https://www.nature.com/articles/nature24270.epdf?author_access_token=VJXbVjaSHxFoctQQ4p2k4tRgN0jAjWel9jnR3ZoTv0PVW4gB86EEpGqTRDtpIz-2rmo8-KG06gqVobU5NSCFeHILHcVFUeMsbvwS-lxjqQGg98faovwjxeTUgZAUMnRQ)

> Expand and evaluate (Fig. 2b). The leaf node sL is added to a queue for neural net-work evaluation, (di(p), v) =  fθ(di(sL)), where di is a dihedral reflection or rotation selected uniformly at random from i in [1..8].

and their new [paper](https://arxiv.org/abs/1712.01815)

> The rules of Go are invariant to rotation and reflection. This fact was exploited in AlphaGo
and AlphaGo Zero in two ways. First, training data was augmented by generating 8 symmetries
for each position. Second, during MCTS, board positions were transformed using a randomly
selected rotation or reflection before being evaluated by the neural network, so that the MonteCarlo evaluation is averaged over different biases
