### ISSUE TITLE
Cannot use multiple GPUs in self-play

### ISSUE THREAD

**Issue by AranKomat** [mokemokechicken/reversi-alpha-zero#57]
@mokemokechicken @gooooloo I added one more GPU. However, the added GPU has 0% usage rate, and doubling prediction_queue_size, parallel_search_num and multi_process_num doesn't make a difference. Also, has asynchronous training, or one GPU doing grad updates while other GPUs doing self-play and weights are synced after each grad update, been implemented in @gooooloo 's algorithm?

**Comment by gooooloo** [comment]
@AranKomat 

>  Also, has asynchronous training, or one GPU doing grad updates while other GPUs doing self-play and weights are synced after each grad update, been implemented in @gooooloo 's algorithm?

Yes, I am using GPUs this way. 1 for opt, 1 for evaluator( for AlphaGoZero way only), others for selfplay. Each self-play GPU serves several self play processes. Actually I don't have specific codes for this "distributed architecture"; since my each GPU is in a seperated Docker instance, all I need to do is triggering different "python ***" commond in each different Docker instance.

If you are using 2 GPUs in one same machine, have you tried `CUDA_VISIABLE_DEVICES=0 python *** opt ***` and `CUDA_VISIBLE_DEVICES=1 python **** self ***` ?

**Comment by AranKomat** [comment]
@gooooloo Thanks for your advice! It worked as expected!

**Comment by gooooloo** [comment]
@AranKomat cool.
